# Generated by Django 4.2.4 on 2023-08-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'intents',
            },
        ),
        migrations.CreateModel(
            name='QuestionForChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amend_data.intent')),
            ],
            options={
                'db_table': 'questions_for_chatbot',
            },
        ),
        migrations.CreateModel(
            name='AnswerForChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amend_data.intent')),
            ],
            options={
                'db_table': 'answers_for_chatbot',
            },
        ),
    ]
