# Generated by Django 4.2.4 on 2023-08-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0002_intent_questionforchatbot_answerforchatbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesAnswer', models.FileField(upload_to='answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'FilesAnswer',
            },
        ),
        migrations.CreateModel(
            name='FilesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesQuestion', models.FileField(upload_to='questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'FilesQuestion',
            },
        ),
    ]
