# Generated by Django 4.2.4 on 2023-08-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0003_filesanswer_filesquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Out_of_scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_of_scope', models.CharField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'out_of_scope',
            },
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_primary', models.CharField(max_length=1000)),
                ('synonym', models.CharField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sysnonyms',
            },
        ),
    ]
