# Generated by Django 4.2.4 on 2023-08-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0004_out_of_scope_synonyms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='out_of_scope',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='out_of_scope',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='synonyms',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='synonyms',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
