# Generated by Django 4.2.4 on 2023-08-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0005_rename_create_at_out_of_scope_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_convert', models.FileField(upload_to='file_convert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'file_convert',
            },
        ),
    ]
