# Generated by Django 4.2.4 on 2023-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0007_modelrasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrasa',
            name='isActivate',
            field=models.BooleanField(default=False),
        ),
    ]
