# Generated by Django 4.2.4 on 2023-09-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0008_modelrasa_isactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='intent_id',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='amend_data.intent'),
            preserve_default=False,
        ),
    ]
