# Generated by Django 4.2.4 on 2023-10-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0009_image_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='intent_detail',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
