# Generated by Django 4.2.4 on 2023-10-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0010_intent_intent_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_answer', models.CharField(max_length=1000)),
                ('id_answer', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('intent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amend_data.intent')),
            ],
            options={
                'db_table': 'sort_answer',
            },
        ),
    ]
