# Generated by Django 4.2.4 on 2023-10-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0011_sortanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='intent_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='sortanswer',
            name='sort',
            field=models.IntegerField(unique=True),
        ),
    ]
