# Generated by Django 4.2.4 on 2023-10-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amend_data', '0012_alter_intent_intent_name_alter_sortanswer_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortanswer',
            name='sort',
            field=models.IntegerField(),
        ),
    ]
